# Generated by Django 2.0.5 on 2019-09-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feeback_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('diseasetype', models.CharField(max_length=50)),
                ('feedback', models.CharField(blank=True, max_length=500, null=True)),
                ('stars1', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MRI_ScanValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysisvalue', models.CharField(max_length=5000)),
                ('uniquecontors', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
