# Generated by Django 2.0.5 on 2019-09-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mri_scanvalue',
            name='Brain_Userd',
            field=models.ForeignKey(default='', on_delete='cascade', to='patients.UserRegistration'),
            preserve_default=False,
        ),
    ]
