# Generated by Django 2.0.5 on 2019-09-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_mri_scanvalue_brain_userd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_MRIimageScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(max_length=500)),
                ('Patient_Age', models.IntegerField()),
                ('AnyauseofSymptoms', models.CharField(max_length=1000)),
                ('UploadBrainMRIImage', models.ImageField(upload_to='')),
                ('Recommendation', models.CharField(max_length=5000)),
            ],
        ),
    ]
