# Generated by Django 2.0.5 on 2019-09-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=100)),
                ('doctoraddress', models.CharField(max_length=500)),
                ('mobileno', models.CharField(max_length=20)),
                ('emailid', models.CharField(max_length=100)),
                ('doctorage', models.IntegerField()),
                ('doctorgender', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=200)),
            ],
        ),
    ]
