# Generated by Django 2.0.5 on 2019-09-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_doctors',
            name='doctorID',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
