# Generated by Django 2.0.5 on 2019-09-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_add_doctors_doctorid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_Doctors',
        ),
    ]
