# Generated by Django 2.0.5 on 2019-09-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_add_doctors_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_MRI_ScanValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysisvalue', models.CharField(max_length=5000)),
                ('uniquecontors', models.CharField(max_length=5000)),
            ],
        ),
    ]
